foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.flatpages import views as flatpages_views

from foodgram import views
from recipe.views import index


handler404 = views.page_not_found
handler500 = views.server_error


urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", include("django.contrib.flatpages.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("recipes/", include("recipe.urls")),
    path("api/", include("api_v1.urls")),
    path("", index, name="index"),
]

urlpatterns += [
    path(
        "about-author/",
        flatpages_views.flatpage,
        {"url": "/about-author/"},
        name="about-author",
    ),
    path(
        "about-project/",
        flatpages_views.flatpage,
        {"url": "/about-project/"},
        name="about-project",
    ),
    path(
        "technologies/",
        flatpages_views.flatpage,
        {"url": "/technologies/"},
        name="technologies",
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

recipe/urls.py
from django.urls import path

from . import views

app_name = "recipes"

urlpatterns = [
    path("create/", views.recipe_create, name="recipe_create"),
    path("purchases/", views.purchases_index, name="purchases_index"),
    path(
        "purchases/<int:recipe_id>/",
        views.purchases_delete,
        name="purchases_delete",
    ),
    path("download/", views.download, name="download"),
    path("edit/<int:recipe_id>/", views.recipe_edit, name="recipe_edit"),
    path("delete/<int:recipe_id>/", views.recipe_delete, name="recipe_delete"),
    path(
        "<str:username>/favorites/",
        views.favorite_recipes,
        name="favorite_recipes",
    ),
    path(
        "<str:username>/<int:recipe_id>/",
        views.recipe_view,
        name="recipe_view",
    ),
    path("<str:username>/follow/", views.follow_index, name="follow_index"),
    path("<str:username>/", views.profile, name="profile"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
]

recipe/models.py
from django.db import models
from django.contrib.auth import get_user_model

from .managers import RecipeManager, FavoriteRecipeManager

User = get_user_model()


class Ingredient(models.Model):
    name = models.CharField(
        max_length=5000, verbose_name="ingredient's name", unique=True
    )
    measure = models.CharField(max_length=100, verbose_name="measurement unit")

    class Meta:
        verbose_name = "Ingredient"
        verbose_name_plural = "Ingredients"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Tag(models.Model):
    value = models.CharField("Value", max_length=10, unique=True)
    name = models.CharField("Visible name", max_length=25, unique=True)
    color = models.CharField("Color", max_length=10)

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return self.name


class Recipe(models.Model):
    name = models.CharField(max_length=200, verbose_name="recipe's name")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="recipes"
    )
    tag = models.ManyToManyField(
        Tag, through="RecipeTag", related_name="recipes"
    )
    ingredients = models.ManyToManyField(
        Ingredient,
        through="RecipeIngredient",
        through_fields=("recipe", "ingredient"),
        verbose_name="ingredients",
    )
    description = models.TextField()
    pub_date = models.DateTimeField(
        auto_now=True, db_index=True, verbose_name="publishing date"
    )
    cook_time = models.PositiveSmallIntegerField(
        verbose_name="cook time",
        null=False,
        default=10,
        help_text="Add cook time in minutes",
    )
    picture = models.ImageField(
        upload_to="recipe/", verbose_name="picture of the recipe"
    )
    objects = RecipeManager()

    class Meta:
        verbose_name = "Recipe"
        verbose_name_plural = "Recipes"
        ordering = ["-pub_date"]

    def __str__(self):
        return self.name


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="recipe_ingredients"
    )

    ingredient = models.ForeignKey(
        Ingredient, on_delete=models.PROTECT, related_name="recipe_ingredients"
    )

    weight = models.PositiveSmallIntegerField(
        verbose_name="weight_ingredients",
        null=False,
        default=10,
        help_text="Add needed weight for the recipe",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["recipe", "ingredient"], name="recipe_unique"
            )
        ]
        verbose_name = "Recipe Ingredient"
        verbose_name_plural = "Recipes Ingredients"
        ordering = ["recipe"]

    def __str__(self):
        return self.ingredient.name


class RecipeTag(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        verbose_name="Recipe title",
        related_name="recipe_tags",
    )
    tag = models.ForeignKey(
        Tag,
        on_delete=models.CASCADE,
        verbose_name="Tag name",
        related_name="recipe_tags",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["recipe", "tag"], name="recipe_tag_unique"
            )
        ]
        verbose_name = "Recipe tags"
        verbose_name_plural = "Recipe tags"


class FavoriteRecipe(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="liker"
    )
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="favorite_recipes"
    )
    objects = FavoriteRecipeManager()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "recipe"], name="favorite_unique"
            )
        ]
        verbose_name = "Favorite Recipe"
        verbose_name_plural = "Favorite Recipes"
        ordering = ["user"]

    def __str__(self):
        return f"favorite recipe - {self.recipe.name}"


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="follower"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="follow_unique"
            )
        ]
        ordering = [
            "-id",
        ]


class Purchase(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="purchases"
    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "recipe"], name="purchase_unique"
            )
        ]
        verbose_name = "Shopping List"
        verbose_name_plural = "Shopping Lists"
        ordering = ["recipe"]

recipe/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from .models import Recipe, RecipeIngredient
from recipe.models import Ingredient
from recipe.utils import get_ingredients


class RecipeForm(forms.ModelForm):
    picture = forms.ImageField(required=True, label="Add an image")

    def save(self, commit=True):
        request = self.initial["request"]
        recipe = super().save(commit=False)
        recipe.author = request.user
        recipe.save()

        ingredients = get_ingredients(request)
        for item in ingredients:
            RecipeIngredient.objects.create(
                weight=ingredients[item],
                recipe=recipe,
                ingredient=get_object_or_404(Ingredient, name=item),
            )
        self.save_m2m()
        return recipe

    class Meta:
        model = Recipe
        fields = (
            "name",
            "description",
            "cook_time",
            "picture",
            "tag",
        )

        labels = {
            "name": "Recipe title",
            "cook_time": "Total cooking time",
            "description": "Description",
            "picture": "Add an image",
        }

recipe/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from reportlab.pdfgen import canvas

from foodgram.settings import OBJECT_PER_PAGE
from recipe.forms import RecipeForm
from recipe.models import (
    User,
    Recipe,
    Follow,
    Purchase,
    RecipeIngredient,
    FavoriteRecipe,
)
from recipe.utils import generate_shop_list, pagination, is_negative_weight

INGREDIENT_VALUE_ERROR = "Value should be greater than 0"

def index(request):
    """Отображение главной страницы."""

    active_index = True
    tags = request.GET.getlist("filters")
    recipe_types = Recipe.objects.tag_filter(tags)
    paginator, page = pagination(request, recipe_types, OBJECT_PER_PAGE)
    context = {
        "page": page,
        "paginator": paginator,
        "active_index": active_index,
    }
    return render(request, "recipe/index.html", context)


@login_required
def recipe_create(request):
    """ Cоздание нового рецепта. """

    active_create = True
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
        initial={"request": request},
    )
    context = {}
    if is_negative_weight(request):
        context["ingredient_value_message"] = INGREDIENT_VALUE_ERROR
    elif form.is_valid():
        form.save()
        return redirect("index")

    context.update({
        "name": "name",
        "form": form,
        "description": "description",
        "cook_time": "cook_time",
        "picture": "picture",
        "active_create": active_create,
    })
    return render(request, "recipe/recipe_action.html", context)


@login_required
def recipe_edit(request, recipe_id):
    """Cтраница редактирования рецепта."""

    recipe = get_object_or_404(Recipe, id=recipe_id)
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
        instance=recipe,
        initial={"request": request},
    )
    data = {}
    if is_negative_weight(request):
        data["ingredient_value_message"] = INGREDIENT_VALUE_ERROR
    elif form.is_valid():
            RecipeIngredient.objects.filter(recipe=recipe).delete()
            form.save()
            return redirect("index")
    data["form"] = form
    data["recipe"] = recipe

    return render(
        request, "recipe/recipe_action.html", data
    )

@login_required
def recipe_delete(request, recipe_id):
    """Удаление рецепта."""

    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.user == recipe.author:
        recipe.delete()
    return redirect("index")


def recipe_view(request, username, recipe_id):
    """Страница просмотра рецепта."""

    recipe = get_object_or_404(Recipe, id=recipe_id)
    author = get_object_or_404(User, username=username)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
    return render(
        request,
        "recipe/recipe_view.html",
        {
            "recipe": recipe,
            "following": following,
        },
    )


@login_required
def favorite_recipes(request, username):
    """Страница избранных рецептов."""

    active_favorites = True
    tag_value = request.GET.getlist("filters")
    favorite_list = FavoriteRecipe.objects.favorite_recipe(
        request.user, tag_value
    )
    paginator, page = pagination(request, favorite_list, OBJECT_PER_PAGE)
    context = {
        "page": page,
        "paginator": paginator,
        "active_favorites": active_favorites,
    }
    return render(request, "recipe/favorite.html", context)


@login_required
def profile(request, username):
    """Страница автора рецептов."""

    author = get_object_or_404(User, username=username)
    tag_value = request.GET.getlist("filters")
    recipe_tags = Recipe.objects.tag_filter(tag_value).filter(author=author)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=author
        ).exists()

    paginator, page = pagination(request, recipe_tags, OBJECT_PER_PAGE)
    return render(
        request,
        "recipe/author_profile.html",
        {
            "page": page,
            "paginator": paginator,
            "following": following,
            "author": author,
        },
    )


@login_required
def follow_index(request, username):
    """Страница мои подписки."""

    active_follow = True
    user_follow = get_object_or_404(User, username=username)
    authors = Follow.objects.filter(user=user_follow)
    paginator, page = pagination(request, authors, OBJECT_PER_PAGE)
    return render(
        request,
        "recipe/my_follow.html",
        {
            "page": page,
            "paginator": paginator,
            "user_follow": user_follow,
            "active_follow": active_follow,
            "authors": authors,
        },
    )


@login_required
def purchases_index(request):
    """Страница списка покупок."""

    active_purchases = True
    purchases = Purchase.objects.filter(user=request.user)
    return render(
        request,
        "recipe/shop_list.html",
        {"purchases": purchases, "active_purchases": active_purchases},
    )


@login_required
def purchases_delete(request, recipe_id):
    """Удаление рецепта из списка покупок."""

    recipe = get_object_or_404(Recipe, id=recipe_id)
    Purchase.objects.filter(user=request.user, recipe=recipe).delete()
    return redirect("recipes:purchases_index")


@login_required
def download(request):
    """Скачать список покупок в PDF файл."""

    result = generate_shop_list(request)
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = 'attachment; filename="purchases.pdf"'
    p = canvas.Canvas(response)
    top_line = 810
    p.drawString(10, top_line, "Purchases:")

    for i in result:
        top_line -= 20
        p.drawString(10, top_line, i)
    p.showPage()
    p.save()
    return response

recipe/templates/recipe/favorite.html
{% extends "base.html" %}
{% block title %} favorite {% endblock %}

{% block content %}

{% load recipe_filters %}

{% csrf_token %} {# необходим для передачи POST запроса в API из JS #}

 <div class="main__header">
    <h1 class="main__title">My Favorite Recipes</h1>
    <ul class="tags">
        {% include "recipe/includes/recipe_tags.html"  %}
    </ul>
</div>

<div class="card-list">
    {% for recipe in page %}
        {% include "recipe/includes/recipe_item.html" with recipe=recipe %}
    {% endfor %}
</div>

{% if page.has_other_pages %}
    {% include "includes/paginator.html" with items=page paginator=paginator%}
{% endif %}

{% load static %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/favorite.js' %}"></script>

{% endblock %}

recipe/templates/recipe/my_follow.html
{% extends "base.html" %}
{% block title %} My subscriptions {% endblock %}

{% block content %}
{% csrf_token %}
{% load recipe_filters user_filters %}

<div class="main__header">
    <h1 class="main__title">My subscriptions</h1>
</div>

<div class="card-list">
    {% for item in page %}
    <div class="card-user" data-author="{{ item.author.id }}">
        <div class="card-user__header">
            <h2 class="card-user__title">{{ item.author.first_name }} {{ item.author.last_name }}</h2>
        </div>
        <div class="card-user__body">
            <ul class="card-user__items">

                {% for elem in item.author.recipes.all|slice:":3" %}
                <li class="card-user__item">
                    <div class="recipe">
                        <img src="{{ elem.picture.url }}" alt="{{ elem.name }}" class="recipe__image">
                        <h3 class="recipe__title">{{ elem.name }}</h3>
                        <p class="recipe__text"><span class="icon-time"></span> {{ elem.cook_time }} minutes</p>
                    </div>
                </li>
                {% endfor %}
                <li class="card-user__item">
                    {% if item.author.recipes.count > 3 %}
                    <a href="{% url 'recipes:profile' item.author.username %}" class="card-user__link link">Find {{ item.author.recipes.count|subtract:3 }} more...</a>
                    {% endif %}
                </li>
            </ul>
        </div>

        <div class="card-user__footer">
            <button class="button button_style_light-blue button_size_auto" name="subscribe"><span class="icon-check button__icon"></span>Unfollow </button>
        </div>
    </div>
    {% endfor %}
</div>

    <!-- Вывод паджинатора -->
    {% if page.has_other_pages %}
            {% include "includes/paginator.html" with items=page paginator=paginator %}
    {% endif %}


    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/MyFollow.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/myFollow.js' %}"></script>

{% endblock %}

recipe/templates/recipe/recipe_action.html
{% extends "base.html" %}
{% block title %} {% if active_create %} Create Recipe {% else%} Edit recipe {% endif %} {% endblock %}

{% block content %}

{% load widget_tweaks %}
{% load recipe_filters %}

<div class="main__header">
    <h1 class="main__title">
        {% if active_create %} Create Recipe {% else %}  Edit Recipe {% endif %}
    </h1>
</div>

<div class="form-container">
    <form class="form"
          action="{% if active_create %} {% url 'recipes:recipe_create' %} {% else%} {% url 'recipes:recipe_edit' recipe_id=recipe.id %} {% endif %}"
          method="post"
          enctype="multipart/form-data">


        {% csrf_token %}
        <!-- Recipe Name -->
        <div class="form__group">
            <label for="id_name" class="form__label">Recipe title</label>
            <div class="form__field-group">
                {{ form.name|add_class:"form__input" }}
                <span class="form__error"></span>
            </div>
        </div>

        <!-- Recipe Tags -->
        <div class="form__group">
            <p class="form__label">Recipe Type</p>
            <div class="form__field-group">
                <div class="tags">


                    {% for tag in form.fields.tag.choices.queryset  %}
                        <div class="tags__item">
                            <input
                                type="checkbox"
                                name="tag"
                                value ="{{ tag.id }}"
                                id="id_{{ tag.value }}"
                                class="tags__checkbox tags__checkbox_style_{{ tag.color }}" {% if tag|is_in_type:recipe %} checked {% endif %}>

                            <label for="id_{{ tag.value }}" class="tags__label">{{ tag.name }}</label>
                        </div>
                        {% endfor %}
                </div>
                <span class="form__error"></span>
            </div>
        </div>

        <!-- Recipe Ingredients   -->
        <div class="form__group">
            <label for="nameIngredient" class="form__label">Ingredients</label>
            <div class="form__field-group">
                <div class="form__field-group-ingredientes">
                    <div class="form__dropdown">
                        <input type="text" id="nameIngredient" class="form__input">
                        <div class="form__dropdown-items"></div>
                    </div>
                    <input type="number" id="cantidad" class="form__input" min="1">
                    <label for="cantidad" class="form__label" id="cantidadVal"></label>
                    {% if message %}<div class="non-field-errors" style="color: red">{{ message }}</div>{% endif %}
                </div>
                <div style="color: red"> {{ ingredient_value_message }}</div>
                <div class="form__field-group-ingredientes-container">
                    {% if not active_create %}
                        {% for ingredient_item in recipe.recipe_ingredients.all %}
                            <div class="form__field-item-ingredient" id="ing_{{ ingredient_item.id }}">
                                <span> {{ ingredient_item.ingredient.name }} {{ ingredient_item.weight }} {{ ingredient_item.ingredient.measure }}</span>
                                <span class="form__field-item-delete"></span>
                                <input id="nameIngredient_{{ ingredient_item.id }}" name="nameIngredient_{{ ingredient_item.id }}" type="hidden" value="{{ ingredient_item.ingredient.name }}">
                                <input id="valueIngredient_{{ ingredient_item.id }}" name="valueIngredient_{{ ingredient_item.id }}" type="hidden" value="{{ ingredient_item.weight }}">
                                <input id="unitsIngredient_{{ ingredient_item.id }}" name="unitsIngredient_{{ ingredient_item.id }}" type="hidden" value="{{ ingredient_item.ingredient.measure }}">
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <span class="form__ingredient-link" id="addIng">Add ingredient</span>
                <span class="form__error">
                {% if form.non_field_errors  %}
                {%  for error in form.non_field_errors %}
                    {% if error == 'Add at least one ingredient' %}
                        <div class="non-field-errors">
                            <p class="form-error">{{ error }}</p>
                        </div>
                    {% endif %}
                {% endfor %}
                {% endif %}
                </span>
            </div>
        </div>

        <!-- Recipe Time -->
        <div class="form__group">
            <label for="id_time" class="form__label">Total cooking time</label>
            <div class="form__field-group form__field-group_time">
                {{ form.cook_time|add_class:"form__input" }}
                <label for="id_time" class="form__label">minutes</label>
                <span class="form__error">{{ form.cook_time.errors }}</span>
            </div>
        </div>

        <!-- Recipe Description -->
        <div class="form__group">
            <label for="id_description" class="form__label">Description</label>
            <div class="form__field-group">
                {{ form.description|add_class:"form__textarea" }}
                <span class="form__error"></span>
            </div>
        </div>

        <!-- Recipe File -->
        <div class="form__group">
            <span class="form__label">Add an image</span>
            <div class="form__field-group">
                {{ form.picture|add_class:"form__file-button" }}
                <span class="form__error"></span>
            </div>
        </div>

        <!-- Recipe Button  -->
        <div class="form__footer">
            {% if active_create %}
                    <button class="button button_style_blue">Add recipe</button>
            {% else%}
                <button class="button button_style_blue">Save</button>
                <a style="margin-left: 2.5em" href="{% url 'recipes:recipe_delete' recipe.id %}" class="form__ingredient-link">Delete</a>
            {% endif %}
        </div>
    </form>
</div>

{% load static %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/formRecipe.js' %}"></script>

{% endblock %}

recipe/templates/recipe/recipe_view.html
{% extends "base.html" %}
{% block title %} recipe view {% endblock %}
{% load static %}
{% block content %}

{% load recipe_filters %}
{% load thumbnail %}

<div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
    {% thumbnail recipe.picture "480x480" crop="center" upscale=True as im %}
        <img class="single-card__image" src="{{ im.url }}" alt="{{ recipe.name }}" width="480" height="480">
    {% endthumbnail %}


    <div class="single-card__info">
        {% if user.is_authenticated %}
            <div class="single-card__header-info">
                <h1 class="single-card__title">{{ recipe.name }}</h1>

            <!-- Если рецепт в избранном, подсвечиваем звездочку  -->
                <div class="single-card__favorite">
                {% if recipe|is_favorite:user %}
                    <button class="button button_style_none" name="favorites"><span class="icon-favorite  icon-favorite_big icon-favorite_active"></span></button>
                {% else %}
                    <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite icon-favorite_big"></span></button>
                {% endif %}
                </div>
            </div>
        {% endif %}

        <div class="card__body">
            <ul class="card__items">
                {% for tag in recipe.tag.all %}
                    <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.name }}</span></li>
                {% endfor %}
            </ul>
        </div>

        <div class="single-card__items single-card__items_column">
            <p class="single-card__text"><span class="icon-time"></span>{{ recipe.cook_time }} minutes</p>

            <ul class="single-card__items">
                <li class="single-card__item"><p class="single-card__text"><span class="icon-user"></span>{{ recipe.author}}</p></li>
                {% if recipe.author == user %}
                    <li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'recipes:recipe_edit' recipe_id=recipe.id %}" class="single-card__text">Edit recipe</a></li>
                {% endif %}
            </ul>
        </div>
        <ul class="single-card__items">
            {% if user.is_authenticated %}
                {% if recipe|is_purchase:user %}
                <li class="single-card__item"><button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Recipe added </button></li>
            {% else %}
                <li class="single-card__item"><button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Add to my shopping list</button></li>
            {% endif %}
            {% endif %}
            {% if user != recipe.author %}
                {% if user.is_authenticated %}
                    {% if following %}
                        <button class="button button_style_light-blue button_size" name="subscribe"><span class="icon-check button__icon"></span>Unfollow</button>
                    {% else %}
                        <button class="button button_style_light-blue button_size" name="subscribe" data-out>Follow</button>
                    {% endif %}
                {% endif %}
            {% endif %}
        </ul>

        <div class="single-card__section">
            <h3 class="single-card__section-title">Ingredients:</h3>
            <div class="single-card__items single-card__items_column">
                {% for item in recipe.recipe_ingredients.all %}
                    <p class="single-card__section-item">{{ item.ingredient.name }}  {{ item.weight }} {{ item.ingredient.measure }}</p>
                {% endfor %}
            </div>
        </div>



        <div class="single-card__section">
            <h3 class="single-card__section-title">Description:</h3>
            <p class=" single-card__section-text">{{ recipe.description|linebreaksbr }}</p>
        </div>
    </div>
</div>


{% load static %}
<link rel="stylesheet" href="{% static 'pages/single.css' %}">
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/SingleCard.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

{% if user.is_authenticated %}
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/singlePage.js' %}"></script>
{% else %}
    <script src="{% static 'js/singlePageNotAuth.js' %}"></script>
{% endif %}

{% endblock content %}

recipe/templates/recipe/shop_list.html
{% extends "base.html" %}
{% block title %} Recipes {% endblock %}
{% load static %}

{% block content %}
<div class="main__header">
        <h1 class="main__title">My shopping list</h1>
</div>
<div class="card-list card-list_column">
        <ul class="shopping-list">

            {% for item in purchases %}
            <li class="shopping-list__item" data-id="{{ item.recipe.id }}">
                <div class="recipe recipe_reverse">
                    <img src="{{ item.recipe.picture.url }}" alt="{{ item.recipe.name }}" class="recipe__image">
                    <h3 class="recipe__title">{{ item.recipe.name }}</h3>
                    <p class="recipe__text"><span class="icon-time"></span> {{ item.recipe.cook_time }} minutes</p>
                </div>
                <a href="{% url 'recipes:purchases_delete' item.recipe.id %}" class="shopping-list__button link">Remove</a>
            </li>
            {% empty %}
                <h3 class="text-center">Your shopping list has no recipes yet</h3>
            {% endfor %}
        </ul>
        <a href="{% url 'recipes:download' %}"><button class="button button_style_blue">Download a grocery list</button></a>
</div>


<!-- Загрузка статики -->
{% load static %}
<link rel="stylesheet" href="{% static 'pages/shopList.css' %}">

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/components/ShopList.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/shopList.js' %}"></script>

{% endblock content %}