foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.flatpages import views as flatpages_views

from foodgram import views
from recipe.views import index


handler404 = views.page_not_found
handler500 = views.server_error


urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", include("django.contrib.flatpages.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("recipes/", include("recipe.urls")),
    path("api/", include("api_v1.urls")),
    path("", index, name="index"),
]

urlpatterns += [
    path(
        "about-author/",
        flatpages_views.flatpage,
        {"url": "/about-author/"},
        name="about-author",
    ),
    path(
        "about-project/",
        flatpages_views.flatpage,
        {"url": "/about-project/"},
        name="about-project",
    ),
    path(
        "technologies/",
        flatpages_views.flatpage,
        {"url": "/technologies/"},
        name="technologies",
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

recipe/urls.py
from django.urls import path

from . import views

app_name = "recipes"

urlpatterns = [
    path("create/", views.recipe_create, name="recipe_create"),
    path("purchases/", views.purchases_index, name="purchases_index"),
    path(
        "purchases/<int:recipe_id>/",
        views.purchases_delete,
        name="purchases_delete",
    ),
    path("download/", views.download, name="download"),
    path("edit/<int:recipe_id>/", views.recipe_edit, name="recipe_edit"),
    path("delete/<int:recipe_id>/", views.recipe_delete, name="recipe_delete"),
    path(
        "<str:username>/favorites/",
        views.favorite_recipes,
        name="favorite_recipes",
    ),
    path(
        "<str:username>/<int:recipe_id>/",
        views.recipe_view,
        name="recipe_view",
    ),
    path("<str:username>/follow/", views.follow_index, name="follow_index"),
    path("<str:username>/", views.profile, name="profile"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
]

templates/includes/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'about-project' %}" class="footer__brand link">Groceries Assistant </a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about-author' %}" class="footer__link link">About the Author </a></li>
            <li class="footer__item"><a href="{% url 'technologies' %}" class="footer__link link">Technologies</a></li>
        </ul>
    </div>
</footer>

templates/includes/nav.html
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                {% if user.is_authenticated %}

                    <li class="nav__item {% if active_index %}nav__item_active{% endif %}"><a href="{% url 'index' %}" class="nav__link link">Recipes</a></li>
                    <li class="nav__item {% if active_follow %}nav__item_active{% endif %}"><a href="{% url 'recipes:follow_index' user.username %}" class="nav__link link">My subscriptions</a></li>
                    <li class="nav__item {% if active_create %}nav__item_active{% endif %}"><a href="{% url 'recipes:recipe_create' %}" class="nav__link link">Create Recipe</a></li>
                    <li class="nav__item {% if active_favorites %}nav__item_active{% endif %}"><a href="{% url 'recipes:favorite_recipes' user.username %}" class="nav__link link">Favorites</a></li>
                    <li class="nav__item {% if active_purchases %}nav__item_active{% endif %}"><a href="{% url 'recipes:purchases_index' %}" class="nav__link link">Shopping list
                        <span class="badge badge_style_blue nav__badge" id="counter">{% if user.purchases.count %}{{ user.purchases.count }}{% endif %}</span></a></li>

                {% else %}
                    <li class="nav__item {% if active_page == 'index' %}nav__item_active{% endif %}"><a href="{% url 'index' %}" class="nav__link link">Recipes</a></li>
                {% endif %}
            </ul>
            <ul class="nav__items list">
                {% if user.is_authenticated %}
                    <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Change Password</a></li>
                    <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Sign out</a></li>
                {% else %}
                    <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Log in</a></li>
                    <li class="nav__item"><a href="{% url 'users:signup' %}" class="button button_style_blue">Create my account</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

templates/includes/paginator.html
{% load recipe_filters %}
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        <!--кнопка назад-->
        {% if page.has_previous %}
            <li class="pagination__item"><a class="pagination__link link" href="?{{ request|url_with_get:page.previous_page_number }}">&laquo; Previous </a></li>
        {% else %}
            <li class="pagination__item"><a class="pagination__link link" href="#"></a></li>
        {% endif %}
        <!--номера страниц-->
        {% for number in paginator.page_range %}
            {% if page.number == number %}
                <li class="pagination__item pagination__item_active"><a class="pagination__link link" href="?{{ request|url_with_get:number }}">{{ number }}</a></li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="?{{ request|url_with_get:number }}">{{ number }}</a></li>
            {% endif %}
        {% endfor %}
        <!--кнопка вперед-->
        {% if page.has_next %}
            <li class="pagination__item"><a class="pagination__link link" href="?{{ request|url_with_get:page.next_page_number }}">Next &raquo;</a></li>
        {% else %}
            <li class="pagination__item"><a class="pagination__link link" href="#"></a></li>
        {% endif %}

    </ul>
</nav>